words = [
    "abbrs",
    "avahi",
    "beh",
    "bigword",
    "dfmt",
    "dya",
    "ejp",
    "forgit",
    "gdtoolkit",
    "geoclue",
    "grc",
    "imv",
    "langservers",
    "lenovo",
    "libvirtd",
    "lilyinstarlight",
    "luajit",
    "luarocks",
    "netcoredbg",
    "nls",
    "onst",
    "pkgs",
    "pvu",
    "pynvim",
    "razer",
    "rtkit",
    "rtxpm",
    "slint",
    "snakefmt",
    "sourcekit",
    "stylix",
    "stylua",
    "templ",
    "texlab",
    "thinkpad",
    "txtpbfmt",
    "wjrk",
    "yog",
]
