words = [
    "abbrs",
    "adwaita",
    "avahi",
    "backgroundremoval",
    "batsignal",
    "beh",
    "bigword",
    "bluetui",
    "darkman",
    "dfmt",
    "difft",
    "difftastic",
    "dya",
    "ejp",
    "forgit",
    "gdtoolkit",
    "geoclue",
    "ghostty",
    "grc",
    "hyprls",
    "hyprsunset",
    "imv",
    "kdl",
    "langservers",
    "lenovo",
    "libvirtd",
    "lilyinstarlight",
    "luajit",
    "luarocks",
    "netcoredbg",
    "networkmanagerapplet",
    "nls",
    "onst",
    "pavucontrol",
    "pkgs",
    "pulsemixer",
    "pvu",
    "pynvim",
    "razer",
    "rtkit",
    "rtxpm",
    "sirula",
    "slint",
    "snakefmt",
    "sourcekit",
    "specialisation",
    "stylix",
    "stylua",
    "templ",
    "texlab",
    "thinkpad",
    "txtpbfmt",
    "vreg",
    "waybar",
    "webkitgtk",
    "wezterm",
    "wjrk",
    "yml",
    "yog",
]
