# This is my config :) You will be disappointed with it. I use helix without any
# major changes. The only config I have is for languages which are not setup by
# default to have an lsp. This is to maintain compatability across environments
# and for bragging rights. Have fun with near zero config editing!

theme = "transparent_bg"

[keys.normal.space.t]
"l"= ":theme ayu_light"
"d"= ":theme ayu_dark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
